// 登录
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const DO_LOGIN = "DO_LOGIN";
export const DO_LOGOUT = "DO_LOGOUT";
export const GET_USERINFO = "GET_USERINFO";
export const SET_USERINFO = "SET_USERINFO";
export const SET_PHONE_VERIFY = "SET_PHONE_VERIFY";
export const SET_BELL_MESSAGE_STATUS = "SET_BELL_MESSAGE_STATUS";

// 菜单&权限
export const SET_MENU_PARAMS = "SET_MENU_PARAMS";
export const SET_MENU_PERMISSION = "SET_MENU_PERMISSION";
export const GET_MENU_PERMISSION = "GET_MENU_PERMISSION";
export const GET_MENU_ITEM = "GET_MENU_ITEM";

// 获取区域和城市列表
export const GET_REGION_LIST = "GET_REGION_LIST";
export const CLEAR_REGION_LIST = "CLEAR_REGION_LIST";
export const GET_CITY_LIST = "GET_CITY_LIST";
export const GET_USER_REGION_LIST = "GET_USER_REGION_LIST";
export const GET_USER_CITY_LIST = "GET_USER_CITY_LIST";

// 页面布局
export const SWITCH_LAYOUT = "CHANGE_LAYOUT";
export const SWITCH_SIDEBAR = "CHANGE_SIDEBAR";
export const SWITCH_SIDEBAR_COLLASPE = "SWITCH_SIDEBAR_COLLASPE";

// 车场管理
export const SET_PARKLOT = "SET_PARKLOT";
export const CLEAR_PARKLOT = "CLEAR_PARKLOT";
export const SET_CITY = "SET_CITY";
// 预警权限设置
export const SET_NOTIFY_STATUS = "SET_NOTIFY_STATUS";

// websocket
export const REMOVE_EVENT_LISTENER = "REMOVE_EVENT_LISTENER";
export const INIT_SOCKET = "INIT_SOCKET";
export const DISCONNECT_SOCKET = "DISCONNECT_SOCKET";
export const REMOVE_SOCKET = "REMOVE_SOCKET";
export const GET_SOCKET = "GET_SOCKET";
export const SET_RECONNECT_STATUS = "SET_RECONNECT_STATUS";
export const ERROR_CONNECT_METHOD = "ERROR_CONNECT_METHOD";
export const UPDATE_WARN_HISTORY = "UPDATE_WARN_HISTORY";
export const CLIENT_LOGIN = "CLIENT_LOGIN";

// 进出场监控
export const UPDATE_PARKINGLOT_INFO = "UPDATE_PARKINGLOT_INFO";
export const UPDATE_INTEGRATED_DEV = "UPDATE_INTEGRATED_DEV";
export const UPDATE_PARKINGLOT_ID = "UPDATE_PARKINGLOT_ID";
export const UPDATE_GATE_ID = "UPDATE_GATE_ID";
export const UPDATE_GATE_TYPE = "UPDATE_GATE_TYPE";
export const UPDATE_ALERTMSG_ID = "UPDATE_ALERTMSG_ID";
export const UPDATE_PARKINGLOT_LABEL = "UPDATE_PARKINGLOT_LABEL";
export const GET_PARKINGLOT_LABEL = "GET_PARKINGLOT_LABEL";
export const UPDATE_NORMAL_PARKINGLOT_LIST = "UPDATE_NORMAL_PARKINGLOT_LIST";
export const UPDATE_NORMAL_CITY_ID = "UPDATE_NORMAL_CITY_ID";
export const UPDATE_PLATE_NUMBER = "UPDATE_PLATE_NUMBER";
export const CHECK_PARKING_RECORD = "CHECK_PARKING_RECORD";
export const UPDATE_ALERT_CAR_INST = "UPDATE_ALERT_CAR_INST";

// 闸口事件提醒
export const UPDATE_BELL_MESSAGE_NUM = "UPDATE_BELL_MESSAGE_NUM";
